                    <ul id="pe-thumbs" class="pe-thumbs">                        
                        <li><a href="#"><img src="assets/img/what-we-do/beautyOfBrewing.jpg" alt="Heineken, The Beauty of Brewing" width="290" height="165"><div class="pe-description"><h2>Heineken</h2><p>The Beauty of Brewing. - I helped develop Heinken's 'The Beauty of Brewing'. This is a parallax website that explains the story of...</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/jaguaruk_fearless.jpg" alt="Phone Resq." width="290" height="165"><div class="pe-description"><h2>Jaguar UK</h2><p>Since time, and his predestinated end</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/toughmudder.jpg" alt="Toughmudder, Got the bottle" width="290" height="165"><div class="pe-description"><h2>Volvic</h2><p>Toughmudder, Got the bottle</p></div></a></li>                  
                        <li><a href="#"><img src="assets/img/what-we-do/getwellsoup.jpg" alt="Heinz, Get Well Soup" width="290" height="165"><div class="pe-description"><h2>Heinz</h2><p>, Get Well Soup</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/harrypotter-part2.jpg" alt="Harry Potter Part-2" width="290" height="165"><div class="pe-description"><h2>EA</h2><p>Harry Potter Deathly Hallows, Part-2</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/cadbury-advent-2.jpg" alt="Cadbury Advent Calendar" width="290" height="165"><div class="pe-description"><h2>Cadbury</h2><p>Advent Calendar</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/debenhams.jpg" alt="Debenhams" width="290" height="165"><div class="pe-description"><h2>Debenhams</h2><p>Personal Finance</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/spoilerfoiler.jpg" alt="Breaking Bad Spoiler Foiler" width="290" height="165"><div class="pe-description"><h2>Netflix</h2><p>Breaking Bad Spoiler Foiler</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/heinzMovember.jpg" alt="Heinz HP Movember" width="290" height="165"><div class="pe-description"><h2>Heinz</h2><p>HP Movember</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/volvic-postcards.jpg" alt="Volvic, Touch of Tropical Postcards" width="290" height="165"><div class="pe-description"><h2>time</h2><p>Since time, and his predestinated end</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/enotria-thesocialwine.jpg" alt="Enotria, The Social Wine" width="290" height="165"><div class="pe-description"><h2>Enotria</h2><p>The Social Wine</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/kleenex-collage.jpg" alt="Kleenex Collection" width="290" height="165"><div class="pe-description"><h2>Kleenex</h2><p>Kleenex Collection</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/kleenex-vote.jpg" alt="Kleenex Vote" width="290" height="165"><div class="pe-description"><h2>Kleenex</h2><p>Kleenex Vote</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/bulmers-begin.jpg" alt="Bulmers, Begin with a Bulmers" width="290" height="165"><div class="pe-description"><h2>Bulmers</h2><p>Begin with a Bulmers</p></div></a></li>            
                        <li><a href="#"><img src="assets/img/what-we-do/cuppaclub.jpg" alt="PG tips, Cuppa Club" width="290" height="165"><div class="pe-description"><h2>PG tips</h2><p>Cuppa Club</p></div></a></li>                                          
                        <li><a href="#"><img src="assets/img/what-we-do/sheba.jpg" alt="Sheba UK" width="290" height="165"><div class="pe-description"><h2>Sheba UK</h2><p></p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/myCallaway.jpg" alt="MyCallaway" width="290" height="165"><div class="pe-description"><h2>Callaway</h2><p>My Callaway</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/harrypotter-part1.jpg" alt="Harry Potter Part-1" width="290" height="165"><div class="pe-description"><h2>EA</h2><p>Harry Potter Deathly Hallows, Part-1</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/supportyourteam.jpg" alt="London 2012 Support your Team" width="290" height="165"><div class="pe-description"><h2>London Olympics 2012</h2><p>London 2012 Support your Team</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/playboyUK.jpg" alt="Playboy UK" width="290" height="165"><div class="pe-description"><h2>Playboy</h2><p>Playboy UK site</p></div></a></li>                                                
                        <li><a href="#"><img src="assets/img/what-we-do/pulse.jpg" alt="London 2012 Pulse" width="290" height="165"><div class="pe-description"><h2>London Olympics 2012</h2><p>London 2012 Pulse</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/pgtipscuppaclub2.jpg" alt="PG tips Cuppa Club 2" width="290" height="165"><div class="pe-description"><h2>PG tips</h2><p>Cuppa Club 2</p></div></a></li>                        
                        <li><a href="#"><img src="assets/img/what-we-do/hotelsdotcom.jpg" alt="Hotels.com Photo competition" width="290" height="165"><div class="pe-description"><h2>Hotels.com</h2><p>Photo competition</p></div></a></li>                                                                        
                        <li><a href="#"><img src="assets/img/what-we-do/playboyU.jpg" alt="Playboy U" width="290" height="165"><div class="pe-description"><h2>Playboy U</h2><p>Playboy University</p></div></a></li>
                        
                        
                        <li><a href="#"><img src="assets/img/what-we-do/playboy-thinking-is-sexy.jpg" alt="Playboy Thinking is Sexy" width="290" height="165"><div class="pe-description"><h2>Playboy UK</h2><p>Thinking is Sexy</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/moetMomente.jpg" alt="Moet Momente" width="290" height="165"><div class="pe-description"><h2>Moet and Chandon</h2><p>Moet Momente</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/bulmers.jpg" alt="Bulmers, New Blends" width="290" height="165"><div class="pe-description"><h2>Bulmers</h2><p>New Blends</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/lenovo.jpg" alt="Lenovo The Year of the Do" width="290" height="165"><div class="pe-description"><h2>Lenovo</h2><p>The Year of the Do</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/pgTips.jpg" alt="PG Tips Warm up Britain" width="290" height="165"><div class="pe-description"><h2>PG Tips</h2><p>Warm up Britain</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/evian.jpg" alt="Live young this January this January with Evian" width="290" height="165"><div class="pe-description"><h2>Evian</h2><p>Live young this January this January with Evian</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/jaguar_calendar.jpg" alt="Jaguar Desire Calendar" width="290" height="165"><div class="pe-description"><h2>Jaguar UK</h2><p>Desire Calendar</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/playboyCorp.jpg" alt="Playboy UK Corporate" width="290" height="165"><div class="pe-description"><h2>Playboy UK</h2><p>Corporate site</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/redbull.jpg" alt="Redbull, Our Editions" width="290" height="165"><div class="pe-description"><h2>Redbull </h2><p>Our Editions</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/pringles.jpg" alt="Pringle Help the Oversharers" width="290" height="165"><div class="pe-description"><h2>Pringle </h2><p>Help the Oversharers</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/tiger.jpg" alt="Tiger Beer Zodia Pairs" width="290" height="165"><div class="pe-description"><h2>Tiger Beer</h2><p>Zodia Pairs</p></div></a></li>
                        <li><a href="#"><img src="assets/img/what-we-do/jaguar_cricket.jpg" alt="Jaguar Cricket India" width="290" height="165"><div class="pe-description"><h2>Jaguar </h2><p>Cricket India</p></div></a></li>
                  </ul>
